name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/AI-Project-Mentor
            
            # Pull latest code
            git pull origin main
            
            # Update Backend
            cd backend
            npm install
            npx prisma db push
            npx prisma generate
            pm2 restart backend
            
            # Update Frontend
            cd ../frontend
            npm install
            npm run build
            pm2 restart frontend
